### ISSUE TITLE
Host a game.

### ISSUE THREAD

**Issue by Dycool** [alexis-evelyn/Crewmate#5]
When I try to create a game, it doesnt work and I get this error.
`java.io.IOException: Invalid argument
        at java.base/java.io.RandomAccessFile.seek0(Native Method)
        at java.base/java.io.RandomAccessFile.seek(RandomAccessFile.java:591)
        at me.alexisevelyn.crewmate.packethandler.packets.reliable.HostSettingsPacket.getCodeFromList(HostSettingsPacket.java:122)
        at me.alexisevelyn.crewmate.packethandler.packets.reliable.HostSettingsPacket.getNewGameSettings(HostSettingsPacket.java:50)
        at me.alexisevelyn.crewmate.packethandler.packets.GamePacket.handleAmongUsPacket(GamePacket.java:48)
        at me.alexisevelyn.crewmate.packethandler.HazelPacket.handlePacket(HazelPacket.java:56)
        at me.alexisevelyn.crewmate.Server.parsePacketAndReply(Server.java:137)
        at me.alexisevelyn.crewmate.Server.run(Server.java:100)`

**Comment by alexis-evelyn** [comment]
The server's not ready for public use yet. I am shocked the that word list chooser is broken though, so I'll have to see what's up with that.

**Comment by alexis-evelyn** [comment]
Fixed the issue. Server now let's you join the lobby, but it's still not ready for the public.
